export const routes = {
    region:'my-way',
    transport: {
        aviationAndRailway: "transport/aviation-and-railway",
        citySchedule: "transport/city-schedule",
        scooterRental: "transport/scooter-rental",
        trafficConditions: "transport/traffic-conditions",
    },
    accommodation: {
        hotels: "accommodation/hotels",
        vacationHomes: "accommodation/vacation-homes",
        sanatoriums: "accommodation/sanatoriums",
        coworkingCenters: "accommodation/coworking-centers",
    },
    food: {
        delivery: "food/delivery",
        groceryDelivery: "food/grocery-delivery",
        restaurants: "food/restaurants",
        stores: "food/stores",
    },
    tourism: {
        routes: "tourism/routes",
        guides: "tourism/guides",
        natureReserves: "tourism/nature-reserves",
        virtualMuseum: "tourism/virtual-museum",
        panoramas: "tourism/panoramas",
        events: "tourism/events",
        placesToGo: "tourism/places-to-go",
        childrensEntertainment: "tourism/childrens-entertainment",
    },
    government: {
        institutions: "government/publicServices",
        post: "government/publicServices",
        banks: "government/publicServices",
        emergencyServices: "government/publicServices",
        police: "government/publicServices",
        utilities: "government/publicServices",
        taxServices: "government/publicServices",
        notariesAndLawyers: "government/publicServices",
    },
    health: {
        pharmacies: "health/pharmacies",
        hospitals: "health/hospitals",
        sports: "health/sports",
        events: "health/events",
    },
    education: {
        institutions: "education/institutions",
        childrenClasses: "education/children-classes",
        adultCourses: "education/adult-courses",
    },
    services: {
        clothingRepair: "services/clothing-repair",
        deviceRepair: "services/device-repair",
        recycling: "services/recycling",
        waterAndGas: "services/water-and-gas",
        classifieds: "services/classifieds",
    },
    mobile: {
        appDownload: "mobile/app-download",
        wifiAccess: "mobile/wifi-access",
        operators: "mobile/operators",
    },
};
